sudo: false
language: go
git:
    depth: 1
install: go get -v github.com/gohugoio/hugo
script: hugo
deploy:
    provider: pages
    skip_cleanup: true
    github_token: 0757d8b1ec64a73a94bb24ec284a5d28fb40b9c8
    on:
        branch: master
    local_dir: public
    repo: chengshuyi/csy.github.io
    fqdn: <custom-domain-if-needed>
    target_branch: master
    email: c15271843451@outlook.com
    name: chengshuyi