sudo: false
language: go
install: 
  - wget https://github.com/gohugoio/hugo/releases/download/v0.68.3/hugo_extended_0.68.3_Linux-64bit.tar.gz
  - tar -xzvf hugo_extended_0.68.3_Linux-64bit.tar.gz
  - chmod +x hugo
  - export PATH=$PATH:$PWD
  - hugo version
script: hugo -t meme
deploy:
    provider: pages
    skip_cleanup: true
    github_token: $token
    on:
        branch: master
    local_dir: public
    repo: chengshuyi/csy.github.io
    fqdn: <custom-domain-if-needed>
    target_branch: master
    email: c15271843451@outlook.com
    name: chengshuyi

notifications:
  email: false