sudo: false
language: go
git:
    depth: 1
install: go get -v github.com/gohugoio/hugo --tags extended
script: hugo
deploy:
    provider: pages
    skip_cleanup: true
    github_token: $token
    on:
        branch: master
    local_dir: public
    repo: chengshuyi/csy.github.io
    fqdn: <custom-domain-if-needed>
    target_branch: master
    email: c15271843451@outlook.com
    name: chengshuyi

notifications:
  email: false